version: '3.1'

services:
  
  frontend-vue:
    container_name: base-app_frontend-vue
    image: base-app-frontend-vue
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - '80:80'
    networks: 
      - base-app

networks:
  base-app:
    external: true